name: Service Test Pipeline

 

on:
  pull_request:
    types: [opened, synchronize, reopened]    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v1
