name: Service Test Pipeline
on:
 pull_request:
 push:
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v1
    - name: List of Requested Revierwers
      env:
        GITHUB_CONTEXT: ${{ toJson(github.event.pull_request.requested_reviewers) }}              
      run: echo "$GITHUB_CONTEXT"
    - name: Fail if no match found
      env:
        GITHUB_CONTEXT: ${{ toJson(github.event.pull_request.requested_reviewers) }}                         
      if: contains(GITHUB_CONTEXT.*.login, 'shubhamkarnwal123')
      run: echo "Reviewer Found"

     
 
 
