name: Service Test Pipeline
on:
 pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    # Validating the PR branch name (feature/release/hotfix)
    - name: Validating the PR branch name (feature/release/hotfix)     
      if: "!startsWith(github.head_ref, 'feature/') || !startsWith(github.head_ref, 'test') || !startsWith(github.head_ref, 'hotfix/')"  
      run: exit 1 
      

