name: Service Test Pipeline
on:
 pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v1
      
    - name: Validating the PR branch name (feature/release/hotfix)     
      if: "!startsWith(github.head_ref, 'feature') || !startsWith(github.head_ref, 'release') || !startsWith(github.head_ref, 'hotfix')"  
      run: failure()  
        
    - name: List of Requested Revierwers
      env:
        GITHUB_CONTEXT: ${{ toJson(github.event.pull_request.requested_reviewers) }}              
      run: echo "$GITHUB_CONTEXT"
      
    - name: Fails if reviewer not found     
      if: contains(github.event.pull_request.requested_reviewers.*.login, 'shubhamkarnwal123')                      
      run: echo "Reviewer Found" 
      

