name: Service Test Pipeline
on:
 pull_request:
 push:
  
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v1
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github.event.pull_request.requested_reviewers) }}        
      run: echo "$GITHUB_CONTEXT"

     
 
 
