name: Service Test Pipeline
on:
 pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    # Validating the PR branch name (feature/release/hotfix)
    - name: Validating the PR branch name (feature/release/hotfix)
        testbranch = startsWith(github.head_ref, 'test')
      if: startsWith(github.head_ref, 'test') == true
      run: exit 1 
      

